### ISSUE TITLE
Skip Layer different

### ISSUE THREAD

**Issue by dhingratul** [Timen/squeezenext-tensorflow#4]
![image](https://user-images.githubusercontent.com/4759327/48096388-eee1e000-e20e-11e8-866e-c370c5caccf2.png)

From what the paper has, and what the implementation has, there is an extra conv layer in the skip layer, can you explain the difference

**Comment by Timen** [comment]
If you look at the official CAFFE versions here: [https://github.com/amirgholami/SqueezeNext](https://github.com/amirgholami/SqueezeNext) you will see that those convolutions on the skip connections are only used when the number of input and output channels are different. This is necessary otherwise the residual and non residual cannot be added together.
